### ISSUE TITLE
Fatal Error, shutting down servers Error: market and outcome not found

### ISSUE THREAD

**Issue by garethtdavies** [AugurProject/augur-app#99] opened 2018-07-10 21:48 UTC
When starting Augur the application syncs and then just shuts down. Looking in the logs I can see a `Failed to startup: market and outcome not found` error. I had previously created a market. Relevant lines of log file below:

Running MacOS High Sierra 10.13.5. 

```
[2018-07-10 14:41:23.002] [info] Sync with blockchain complete.
[2018-07-10 14:41:23.002] [info] Bulk sync with blockchain complete.
[2018-07-10 14:41:23.003] [info] Starting websocket secure server on port 9002
[2018-07-10 14:41:23.004] [info] Starting websocket server on port 9001
[2018-07-10 14:41:23.356] [info] new block: 5941169 1531258823
[2018-07-10 14:42:43.071] [info] new block: 5941170 1531258825
[2018-07-10 14:42:43.075] [info] Processing 3 logs
[2018-07-10 14:42:43.083] [error] Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 14:42:43.083] [error] Error: market and outcome not found
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 14:42:43.084] [info] Stopping Augur Node Server
[2018-07-10 14:42:43.084] [info] Stopping Augur Node Server
[2018-07-10 14:42:43.084] [info] Stopping Augur UI Server
[2018-07-10 14:42:43.086] [info] Failed to startup: market and outcome not found
```

**Comment by petervecchiarelli** [comment] 2018-07-12 17:40
Duplicate of #78  Please follow progress there

**Closed by petervecchiarelli** 2018-07-12 17:40 UTC
