### ISSUE TITLE
Could not find balance for token decrease

### ISSUE THREAD

**Issue by blacktemplar** [AugurProject/augur-app#88] opened 2018-07-10 17:07 UTC
I am using the augur-app for linux and got the following error today during synchronization (it was already at 100% and then I closed the app and opened it a little bit later again so it had to synchronize).
This also lead to closing the application after the sync finished!

I am using infura as endpoint.

```
[18:57:44.628] [info] new block: 5939956 1531241245
Unhandled rejection Error: Could not find balance for token decrease (token: 0xa87ec9e0e006b90be2c4e3bba3fd17450f7c7034, owner: 0x4e64d886cb5f34c82293093d419c64ea95b8fc49)
    at db.first.from.where.asCallback (/home/bene/git-repos/public/augur-app/node_modules/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:13:29)
    at tryCatcher (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/bene/git-repos/public/augur-app/node_modules/bluebird/js/release/async.js:133:16)
```

**Comment by hoffmabc** [comment] 2018-07-10 17:18
Getting this as well on OSX.

**Comment by hoffmabc** [comment] 2018-07-10 17:30
I checked the sqlite db and the balance is non-existent in the database for the owner specified.

**Comment by xenoexclusive** [comment] 2018-07-10 21:41
Also getting this on Windows 10, just to cover all bases.

**Comment by ldub** [comment] 2018-07-10 23:04
Also got this on OS X: https://pastebin.com/raw/PXi9VhYE

**Comment by petervecchiarelli** [comment] 2018-07-11 20:46
Duplicate of #78  please track progress there.

**Closed** 2018-07-12 06:01 UTC
