### ISSUE TITLE
Failure syncing MAINNET on first run

### ISSUE THREAD

**Issue by levi** [AugurProject/augur-app#188] opened 2018-07-17 22:59 UTC
Augur 1.0.4 currently fails at 23.06% for me right now:

```
Server Error: "insert into `markets` (`category`, `creationBlockNumber`, `creationFee`, `designatedReportStake`, `designatedReporter`, `endTime`, `feeWindow`, `finalizationBlockNumber`, `forking`, `initialReportSize`, `longDescription`, `marketCreator`, `marketCreatorFeeRate`, `marketCreatorFeesBalance`, `marketCreatorMailbox`, `marketCreatorMailboxOwner`, `marketId`, `marketStateId`, `marketType`, `maxPrice`, `minPrice`, `needsDisavowal`, `needsMigration`, `numOutcomes`, `numTicks`, `reportingFeeRate`, `resolutionSource`, `scalarDenomination`, `sharesOutstanding`, `shortDescription`, `tag1`, `tag2`, `universe`, `volume`) values ('FINANCE', 5939341, '0.01', '0.349680582682291667', '0xc408b87d105a33a4632f2be35f234f6bdbdccd32', 0, '0x0000000000000000000000000000000000000000', NULL, 0, NULL, 'Will Tether be found to have been involved in market manipulation in 2018?', '0xc408b87d105a33a4632f2be35f234f6bdbdccd32', '0.02', '0', '0x1aab1a91342a56a005bd4489304eac28b5c80fa3', '0xc408b87d105a33a4632f2be35f234f6bdbdccd32', '0xaac59764ea325352a61d1f2e45eeae77e9948958', 31, 'yesNo', '1', '0', 0, 0, 2, '10000', '0.0001', NULL, NULL, '0', 'Will the cryptocurrency Tether (USDT) be exposed as a scam in 2018?', 'TETHER', 'USDT', '0xe991247b78f937d7b69cfc00f1a487a293557677', '0') - SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime
```

**Comment by petervecchiarelli** [comment] 2018-07-18 16:50
https://app.clubhouse.io/augur/story/14205/github-failure-syncing-mainnet-on-first-run

**Comment by Victor2399** [comment] 2018-07-18 22:09
same

**Comment by BrianSipple** [comment] 2018-07-19 02:45
I'm seeing the same screen @harriswarren is seeing.

**Comment by petervecchiarelli** [comment] 2018-07-20 07:23
Duplicate of #204  Please follow progress there.

**Closed by petervecchiarelli** 2018-07-20 07:23 UTC
