### ISSUE TITLE
Unhandled rejection Error: order not found

### ISSUE THREAD

**Issue by rachyandco** [AugurProject/augur-app#95] opened 2018-07-10 20:25 UTC
Environment
- Augur app Version 1.0.1
- Ubuntu 16.04
- connection to infura

I have the following error log:
```
Unhandled rejection Error: order not found
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/order-filled/index.js:36:37)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

i created a separate issue from https://github.com/AugurProject/augur-app/issues/89 as it is not a `Fatal error`

however it is followed by:

```
[ethrpc] eth_subscribe request failed, fall back to polling for blocks: Method not found
new block: 5940835 1531253672
[22:18:38.965] [info] new block: 5940835 1531253672
Processing 3 logs
[22:18:38.984] [info] Processing 3 logs
Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
[22:18:39.006] [error] Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[22:18:39.007] [error] Error: market and outcome not found
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[22:18:39.029] [info] Stopping Augur Node Server
Stopping Augur Node Server
[22:18:39.030] [info] Stopping Augur Node Server
[22:18:39.030] [info] Stopping Augur UI Server
[22:18:39.031] [info] Failed to startup: market and outcome not found
```

**Comment by rachyandco** [comment] 2018-07-11 07:02
also reported here: https://github.com/AugurProject/augur-app/issues/99

**Comment by petervecchiarelli** [comment] 2018-07-11 20:48
Duplicate of #78  please track progress there.

**Closed** 2018-07-12 17:36 UTC
