### ISSUE TITLE
App should show user's current staked REP and ETH bonds somewhere

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur-app#221] opened 2018-07-21 21:06 UTC
This info is important when you're counting up your assets.

Edit: also Ether reserved in open orders

**Comment by joeykrug** [comment] 2018-07-22 04:53
I had a list of things I think the UI should allow you to see, adding yours + mine together cc @petervecchiarelli 

UI should allow you to:
- see open interest in individual markets
- see total open interest
- see total open interest that will resolve in current fee window
- see total fees in a window
- user's current staked rep and eth bonds
- eth reserved in open orders

**Comment by page1** [comment] 2018-07-23 06:12
I could imagine an expiration calendar summary view for some user info (#of markets, $at risk, Current P&L). This could help a user identify markets that are ending that they don't wish to hold to conclusion. And also help users understand how much longer till the markets are finalized.

If a calendar based view was popular for personal market stats, then maybe there would be demand for a market wide calendar view to help people find bets that fit their timeline. (Although simple filters could also achieve this)

**Comment by adrake33** [comment] 2018-12-04 23:37
Closing as a duplicate of https://github.com/AugurProject/augur/issues/547.

**Closed by adrake33** 2018-12-04 23:37 UTC
