### ISSUE TITLE
0 REP staked after purchasing Participation Token

### ISSUE THREAD

**Issue by Hughesyy** [AugurProject/augur-app#106] opened 2018-07-10 22:52 UTC
I purchased approximately 1.03999999 participation tokens in exchange for REP.

Due to the issues with infura connectivity, I had to re-sync and open the Augur app. My transaction has gone through but it says "0 REP Staked" in the Dispute section.

TxHash: 0xa96852849df918aae3b0a9419c0e02728f7ca92da91a1994228e33a7156b39f9

**Comment by negamax** [comment] 2018-07-11 10:13
@justinbarry  @nuevoalex are those REPs lost?

**Comment by Hughesyy** [comment] 2018-07-11 21:29
I just staked another 1 REP and this time it said "buy confirmed" and when I refreshed the page it still says "0 REP staked".

That's 2 REP which appears to now be lost but I should hope that these have successfully been staked.

TxHash; 0xa3c76f46a4560017e946a3c0dd9696f54e0b0bcd6aae343f99076878ea39d23b

**Comment by nuevoalex** [comment] 2018-07-11 21:35
This is a known issue with Augur Node becoming corrupt during processing. The TXs did occur as you've seen though and your funds are still there in the form of Participation Tokens.

You can confirm this currently by deleting your Augur Node Database here:

Mac OSX : ~/Library/Application\ Support/augur

Windows : %AppData%\augur

Linux : ~/.augur

and syncing.

When the issue is resolved simply reinstalling and syncing will resolve the issue as well.

**Comment by Hughesyy** [comment] 2018-07-11 21:36
Thank you very much, appreciate the work :)

**Comment by petervecchiarelli** [comment] 2018-07-12 17:44
Duplicate of #78 please follow progress there

**Closed by petervecchiarelli** 2018-07-12 17:44 UTC
