### ISSUE TITLE
Error: Could not find balance for token decrease

### ISSUE THREAD

**Issue by aakilfernandes** [AugurProject/augur-app#108] opened 2018-07-10 23:23 UTC
Mac OSX High Sierra 10.13

```
[2018-07-10 19:20:28.548] [error] Fatal Error, shutting down servers Error: Could not find balance for token decrease (token: 0x4a482975a31bb27b9f5cf84c07474b8446bb730c, owner: 0xf10efd52a9f9f434b316963a87dfd4104a33cad0)
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:13:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 19:20:28.549] [error] Error: Could not find balance for token decrease (token: 0x4a482975a31bb27b9f5cf84c07474b8446bb730c, owner: 0xf10efd52a9f9f434b316963a87dfd4104a33cad0)
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:13:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 19:20:28.549] [info] Stopping Augur Node Server
[2018-07-10 19:20:28.550] [info] Stopping Augur Node Server
[2018-07-10 19:20:28.550] [info] Stopping Augur UI Server
[2018-07-10 19:20:28.552] [info] Failed to startup: Could not find balance for token decrease (token: 0x4a482975a31bb27b9f5cf84c07474b8446bb730c, owner: 0xf10efd52a9f9f434b316963a87dfd4104a33cad0)
[2018-07-10 19:20:37.276] [info] network name Mainnet
[2018-07-10 19:20:39.074] [info] Starting Augur UI Server
[2018-07-10 19:20:39.074] [info] Looking for certificate files in /Users/aakilfernandes/Library/Application Support/augur
[2018-07-10 19:20:39.081] [info] SSL is enabled: false
```

**Comment by justinbarry** [comment] 2018-07-11 00:35
Closing. Duplicate of #88.

**Closed by justinbarry** 2018-07-11 00:35 UTC
