### ISSUE TITLE
cannot connect to local parity node

### ISSUE THREAD

**Issue by kevincw01** [AugurProject/augur-app#203] opened 2018-07-19 13:58 UTC
parity is synced.  error message is log is 
`[2018-07-19 06:34:10.267] [info] network name Local
[2018-07-19 06:36:52.517] [info] Stopping Augur Node Server
[2018-07-19 06:36:52.517] [info] Stopping Augur Node Server
[2018-07-19 06:36:52.517] [info] Stopping Augur UI Server
[2018-07-19 06:36:59.299] [info] network name Mainnet
[2018-07-19 06:37:00.759] [info] Starting Augur UI Server
[2018-07-19 06:37:00.760] [info] Looking for certificate files in C:\Users\kevin\AppData\Roaming\augur
[2018-07-19 06:37:06.518] [info] network name Local
[2018-07-19 06:37:13.489] [info] Removing sync-only database: C:\Users\kevin\AppData\Roaming\augur\augur-1-syncing-2.db
[2018-07-19 06:37:13.490] [info] C:\Users\kevin\AppData\Roaming\augur\augur-1-syncing-2.db
[2018-07-19 06:37:13.738] [info] Getting Augur logs from block 5926223 to block 5992448
[2018-07-19 06:37:14.045] [info] new block: 5980003 1531822457
[2018-07-19 06:37:14.060] [info] Processing 4 logs
[2018-07-19 06:37:14.065] [error] Error: Could not find balance for token decrease (token: 0xd5524179cb7ae012f5b642c1d6d700bbaa76b96b, owner: 0xec13edb3ba77d1010bb5905d09b4f6b1644bf9d4)
    at db.first.from.where.asCallback (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\token\decrease-token-balance.js:13:29)
    at tryCatcher (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\kevin\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

**Comment by petervecchiarelli** [comment] 2018-07-20 07:31
https://app.clubhouse.io/augur/story/14285/github-cannot-connect-to-local-parity-node

**Comment by sharkcrayon** [comment] 2018-07-23 11:06
Duplicate of #161

**Closed by sharkcrayon** 2018-07-23 11:06 UTC
