### ISSUE TITLE
Loading screen contains server error - has happened twice

### ISSUE THREAD

**Issue by mitchelluf** [AugurProject/augur-app#200] opened 2018-07-19 05:32 UTC
<img width="1128" alt="augur" src="https://user-images.githubusercontent.com/41412857/42923437-4f63a238-8ada-11e8-80a4-728ffe511397.png">

**Comment by Anastik** [comment] 2018-07-19 18:36
Unfortunately this has been a frequent issue. I'd recommend using augur.casino until the issue can get resolved. If you really want to try running your own node your only options are trying to shut it down and re-open it. Maybe you could try reinstalling. 

But I'd recommend using augur.casino for getting a feel for the Augur UI and conducting small trades to get your feet wet.

**Comment by mitchelluf** [comment] 2018-07-19 19:26
I seem to be having an issue with augur.casino as well. Says the following when I try to connect to the node: 

There was an issue connecting to the nodes, please try again.

**Comment by petervecchiarelli** [comment] 2018-07-20 07:29
https://app.clubhouse.io/augur/story/14284/github-loading-screen-contains-server-error-has-happened-twice

**Comment by sharkcrayon** [comment] 2018-07-23 11:04
Duplicate of #204.

**Closed by sharkcrayon** 2018-07-23 11:04 UTC
