### ISSUE TITLE
Unable to connect to mainnet infura nodes

### ISSUE THREAD

**Issue by Hex-Capital** [AugurProject/augur-app#128] opened 2018-07-11 17:05 UTC
Version: Desktop Windows client version 1.0.2

When clicking connect on the default mainnet settings (Infura node), i get the following error:

There was an issue connecting to the nodes, please try again.

**Comment by petervecchiarelli** [comment] 2018-07-12 18:05
Duplicate of #78 Please follow progress there

**Closed by petervecchiarelli** 2018-07-12 18:05 UTC
