### ISSUE TITLE
[BUG]Can't select/enter a custom buy/sell quantity

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#438] opened 2018-12-23 21:18 UTC
### Summary
This may be on new version of Augur. If that's the case, it's a big break overall. Can't enter a custom quantity on either buy or sell side. It has to be entire order

 ### Steps to reproduce
Tell us how to reproduce the issue.
1. Select any market
2. Select buy/sell from the order book. If you don't have ether to fill entire order you can't proceed!

 ### Expected behavior
Should all option to enter the quantity

 ### Screenshots
![screenshot 2018-12-23 at 21 18 10](https://user-images.githubusercontent.com/1029486/50387603-4a512a00-06f8-11e9-8aec-8b07dbfe1bd1.png)
![screenshot 2018-12-23 at 21 18 04](https://user-images.githubusercontent.com/1029486/50387604-4ae9c080-06f8-11e9-9f37-23a038ce1670.png)

 ### Environment
Mac/Chrome

 ##### If using Augur App:
 - 1.8.6

**Comment by bthaile** [comment] 2018-12-23 23:04
Do you have specific actions to reproduce this issue. I wasn't able to repro. Here are the steps I did:

1. Initial load of augur ui.
2. click on market
3. type on 1 in quantity

The price filled in based on the order book. If you can show a screenshot of the order form when you add quantity that would be helpful. Also if there is any errors in web console. <alt/opt> + <cmd> + i to get to web console.

**Comment by negamax** [comment] 2018-12-23 23:32
@bthaile thanks for checking this, considering Christmas break. So, this is a UX issue rather than functionality but stumped me enough to a) not participate as couldn't figure out and b) downgrade to a previous version.

See the screenshot, the quantity field gives the impression that it's not editable!
![screenshot 2018-12-23 at 23 31 50](https://user-images.githubusercontent.com/1029486/50388336-fbf95680-070a-11e9-8c35-c62b931e57ee.png)

**Comment by bthaile** [comment] 2018-12-23 23:39
Oh, if I understand correctly. You are able to edit the quantity, but because of the appreance of the text in the textbox, you thought it wasn’t editable. 

Is that correct?

**Comment by negamax** [comment] 2018-12-23 23:48
Yes, that's right. I figured this out only now. Fairly small issue but may stump people

**Comment by bthaile** [comment] 2018-12-23 23:51
Thanks for the heads up. We are currently updating the market trading page, we’ll keep this in mind. Also I think we could add  a bit more shadow in the textbox to make it more apparent its editable.

**Comment by adrake33** [comment] 2019-01-02 21:15
Closing this since it is not actually a bug, but I mentioned this to @sharkcrayon and @matt-bullock so they can keep it in mind for the trading page redesign.

**Closed by adrake33** 2019-01-02 21:15 UTC
Labels: Bug
