### ISSUE TITLE
constraint failed: positiveEndTime

### ISSUE THREAD

**Issue by enolan** [AugurProject/augur-app#181] opened 2018-07-17 07:37 UTC
I downloaded the .deb and started syncing a few minutes ago. Syncing appears to have failed, with the following message, at 33.69%.

Server Error: "insert into `markets` (`category`, `creationBlockNumber`, `creationFee`, `designatedReportStake`, `designatedReporter`, `endTime`, `feeWindow`, `finalizationBlockNumber`, `forking`, `initialReportSize`, `longDescription`, `marketCreator`, `marketCreatorFeeRate`, `marketCreatorFeesBalance`, `marketCreatorMailbox`, `marketCreatorMailboxOwner`, `marketId`, `marketStateId`, `marketType`, `maxPrice`, `minPrice`, `needsDisavowal`, `needsMigration`, `numOutcomes`, `numTicks`, `reportingFeeRate`, `resolutionSource`, `scalarDenomination`, `sharesOutstanding`, `shortDescription`, `tag1`, `tag2`, `universe`, `volume`) values ('CRYPTOCURRENCIES', 5944104, '0.01', '0.349680582682291667', '0xa6ac53e2aab6ca452c5ab3aa43ccab6217430cae', 0, '0x0000000000000000000000000000000000000000', NULL, 0, NULL, 'Feel free to consider it a challange', '0xa6ac53e2aab6ca452c5ab3aa43ccab6217430cae', '0.005', '0', '0x5389a4b3db99ea53f535f18e5900b253019cfa86', '0xa6ac53e2aab6ca452c5ab3aa43ccab6217430cae', '0x1c71d0471b1229be3d463393ca7e9db158efb251', 141, 'yesNo', '1', '0', 0, 0, 2, '10000', '0.0001', 'https://twitter.com/elonmusk', NULL, '0', 'Will Elon Musk tweet about this market before July 18th 2018?', 'AUGUR', NULL, '0xe991247b78f937d7b69cfc00f1a487a293557677', '0') - SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime"

Here's a screenshot, if that's helpful.

![screenshot from 2018-07-17 00-34-12](https://user-images.githubusercontent.com/61517/42802941-4b7eaf6e-8959-11e8-985e-bf64a1c2e9da.png)

As of right now, predictions.global lists the Elon Musk tweet market as ending in 3 hours, if that's relevant.

**Comment by enolan** [comment] 2018-07-18 04:48
Yep.

**Comment by petervecchiarelli** [comment] 2018-07-18 16:44
https://app.clubhouse.io/augur/story/14202/github-constraint-failed-positiveendtime

**Comment by epheph** [comment] 2018-07-23 21:59
This should be resolved in 1.0.5 . Ethereum's eth_call has its own internal issues when it is under load, and when backed by a pool of ethereum nodes, which have different perspectives of the network, making an eth_call against a contract on a node that has not yet seen a contract deployment yet will result in "0x". Our middleware was interpreting that error as as "0" instead of recognizing it as a failure. Additionally, it was not retrying, even though the issue is retryable in some circumstances. Both have been fixed in 1.0.5

**Closed by epheph** 2018-07-23 21:59 UTC
