### ISSUE TITLE
Augur App on Mac crashes randomly

### ISSUE THREAD

**Issue by negamax** [AugurProject/augur-app#82] opened 2018-07-10 14:38 UTC
It happens quite often. Could be some sync issue

**Comment by page1** [comment] 2018-07-10 16:28
Just experienced this. Is there a place with logs we should submit to help debug?

**Comment by aakilfernandes** [comment] 2018-07-10 17:03
Can confirm. By "app" I mean the electron app. There's no error or notification, it just silently crashes while browsing localhost.

**Comment by hoffmabc** [comment] 2018-07-10 17:19
You can look in the log for more info:  ~/Library/Logs/augur/log.log

**Comment by aakilfernandes** [comment] 2018-07-10 17:22
@hoffmabc thanks!

Opened up this issue for those who have an "Order Not Found" error

https://github.com/AugurProject/augur-app/issues/89

**Comment by page1** [comment] 2018-07-10 18:35
Looking at ~/Library/Logs/augur/log.log as per @hoffmabc I see an error similar, but slightly different from #89

**Comment by TacoByte** [comment] 2018-07-10 19:34
#77?

**Comment by elie222** [comment] 2018-07-11 11:39
Can confirm this is still happening on 1.0.2. Silently crashes.

**Comment by petervecchiarelli** [comment] 2018-07-11 20:43
Duplicate of #78. Please track progress there.

**Closed by petervecchiarelli** 2018-07-11 20:43 UTC
