### ISSUE TITLE
Transaction doesn't appear in UI

### ISSUE THREAD

**Issue by gabbello** [AugurProject/augur-app#100] opened 2018-07-10 21:56 UTC
I made a buy on s a specific market, but it doesn't appear under "transactions" or "positions" sections.

Transaction on blockchain here: https://etherscan.io/tx/0x5931715b08918d8e32cd0bd557e9de34dd0b5986ba1b06bf7786f7b3e46ab1cd 

Log excerpt below:
```
[00:44:39.937] [info] network name Mainnet
[00:44:41.431] [info] Starting Augur UI Server
[00:44:41.432] [info] Looking for certificate files in /home/gp/.augur
[00:44:41.433] [info] Found localhost certificate and key
[00:44:41.456] [info] SSL is enabled: true
[00:44:41.456] [info] Connecting...
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/augur","ws":"wss://mainnet.infura.io/ws"}
websocket wss://mainnet.infura.io/ws opened
connected to ethereum
/home/gp/.augur/augur-1.db
[00:44:44.643] [info] /home/gp/.augur/augur-1.db
Not leaving at least 5 between batch download and blockstream hand off during re-org can cause data quality issues
[00:44:45.092] [warn] Not leaving at least 5 between batch download and blockstream hand off during re-org can cause data quality issues
Getting Augur logs from block 5941180 to block 5941180
[00:44:45.093] [info] Getting Augur logs from block 5941180 to block 5941180
got 11 logs in blocks { fromBlock: 5941180, toBlock: 5941180 }
[00:44:45.514] [info] 
new block: 5941180 1531259035
[00:44:45.537] [info] new block: 5941180 1531259035
Unhandled rejection Error: Could not find balance for token decrease (token: 0x4a482975a31bb27b9f5cf84c07474b8446bb730c, owner: 0x5e2130c995d105510467c2610893ab8464d3448d)
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:13:29)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

Finished batch load from 5941180 to 5941180
[00:44:46.711] [info] Finished batch load from 5941180 to 5941180
[00:44:46.712] [info] Sync with blockchain complete.
Bulk sync with blockchain complete.
[00:44:46.713] [info] Bulk sync with blockchain complete.
Starting websocket secure server on port 9002
[00:44:46.714] [info] Starting websocket secure server on port 9002
Starting websocket server on port 9001
[00:44:46.718] [info] Starting websocket server on port 9001
Starting blockstream at block  5941181
new block: 5941181 1531259039
[00:44:47.173] [info] new block: 5941181 1531259039
{"id":140,"jsonrpc":"2.0","method":"getCategories","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:44:47.321] [info] {"id":140,"jsonrpc":"2.0","method":"getCategories","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:44:47.883] [info] 
[00:44:48.882] [info] 
[00:44:49.883] [info] 
[00:44:50.882] [info] 
[00:44:51.883] [info] 
[00:44:52.882] [info] 
[00:44:53.885] [info] 
[00:44:54.882] [info] 
[00:44:55.882] [info] 
[00:44:56.882] [info] 
[00:44:57.884] [info] 
[00:44:58.882] [info] 
[00:44:59.884] [info] 
[00:45:00.884] [info] 
[00:45:01.883] [info] 
[00:45:02.884] [info] 
[00:45:03.888] [info] 
{"id":141,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:04.411] [info] {"id":141,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":142,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:04.413] [info] {"id":142,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":143,"jsonrpc":"2.0","method":"getOrders","params":{"orderState":"OPEN","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:04.417] [info] {"id":143,"jsonrpc":"2.0","method":"getOrders","params":{"orderState":"OPEN","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":144,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
[00:45:04.420] [info] {"id":144,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
{"id":145,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
[00:45:04.514] [info] {"id":145,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
[00:45:04.881] [info] 
{"id":146,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
[00:45:05.274] [info] {"id":146,"jsonrpc":"2.0","method":"getProfitLoss","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","startTime":1531172658,"endTime":1531259058,"periodInterval":null}}
[00:45:05.881] [info] 
{"id":147,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.621] [info] {"id":147,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":148,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.623] [info] {"id":148,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":149,"jsonrpc":"2.0","method":"getOrders","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.625] [info] {"id":149,"jsonrpc":"2.0","method":"getOrders","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":150,"jsonrpc":"2.0","method":"getAccountTransferHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","isInternalTransfer":false,"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40"}}
[00:45:06.626] [info] {"id":150,"jsonrpc":"2.0","method":"getAccountTransferHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","isInternalTransfer":false,"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40"}}
{"id":151,"jsonrpc":"2.0","method":"getMarketsCreatedByUser","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.627] [info] {"id":151,"jsonrpc":"2.0","method":"getMarketsCreatedByUser","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":152,"jsonrpc":"2.0","method":"getReportingHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","reporter":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.629] [info] {"id":152,"jsonrpc":"2.0","method":"getReportingHistory","params":{"earliestCreationTime":1531172658,"latestCreationTime":null,"orderState":"ALL","reporter":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:06.882] [info] 
[00:45:07.882] [info] 
new block: 5941182 1531259050
[00:45:08.834] [info] new block: 5941182 1531259050
new block: 5941183 1531259058
[00:45:08.851] [info] new block: 5941183 1531259058
new block: 5941184 1531259069
[00:45:09.047] [info] new block: 5941184 1531259069
[00:45:09.254] [info] 
[00:45:09.881] [info] 
[00:45:10.882] [info] 
{"id":153,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:11.047] [info] {"id":153,"jsonrpc":"2.0","method":"getUserTradingHistory","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":154,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:11.047] [info] {"id":154,"jsonrpc":"2.0","method":"getUserTradingPositions","params":{"account":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":155,"jsonrpc":"2.0","method":"getOrders","params":{"orderState":"OPEN","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:11.048] [info] {"id":155,"jsonrpc":"2.0","method":"getOrders","params":{"orderState":"OPEN","creator":"0xebe2baac77cabaf7eac7abdc910f8d39c097cf40","universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:11.883] [info] 
{"id":156,"jsonrpc":"2.0","method":"getMarkets","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
[00:45:11.959] [info] {"id":156,"jsonrpc":"2.0","method":"getMarkets","params":{"universe":"0xe991247b78f937d7b69cfc00f1a487a293557677"}}
{"id":157,"jsonrpc":"2.0","method":"getMarketsInfo","params":{"marketIds":["0x5e2130c995d105510467c2610893ab8464d3448d","0x4e64d886cb5f34c82293093d419c64ea95b8fc49","0x7d50694af38dcd879255eb5f4dce53e4939c73ac","0xc34941db4fca60d23f7fec90112b8e01831b661f","0x5d192f598ff29318013b3f269ae37590aa75b5f9","0x48628e5832d32ff6e8b722fe820bb9add7ba3c6b","0x212cd5cf0fe10d858b458f31291f4a4a43cf623c","0x0c978d61dd58200cda4687a6810feb69a5069403","0x7e2ad4ec47b03d461422f16af0dad75a33c48e77","0x96b9a092fd1d19d5dff566c07020d6f59d1db79e"]}}
[00:45:12.512] [info] {"id":157,"jsonrpc":"2.0","method":"getMarketsInfo","params":{"marketIds":["0x5e2130c995d105510467c2610893ab8464d3448d","0x4e64d886cb5f34c82293093d419c64ea95b8fc49","0x7d50694af38dcd879255eb5f4dce53e4939c73ac","0xc34941db4fca60d23f7fec90112b8e01831b661f","0x5d192f598ff29318013b3f269ae37590aa75b5f9","0x48628e5832d32ff6e8b722fe820bb9add7ba3c6b","0x212cd5cf0fe10d858b458f31291f4a4a43cf623c","0x0c978d61dd58200cda4687a6810feb69a5069403","0x7e2ad4ec47b03d461422f16af0dad75a33c48e77","0x96b9a092fd1d19d5dff566c07020d6f59d1db79e"]}}
```

**Comment by goyb** [comment] 2018-07-11 10:15
I am encountering the same issue. 

I created a market with the following transaction:
https://etherscan.io/tx/0x5931715b08918d8e32cd0bd557e9de34dd0b5986ba1b06bf7786f7b3e46ab1cd

While it was pending, I was able to view the transaction in the ui ( Portfolio >  Transactions ). However, as soon as the transaction was confirmed it got lost. 

It doesnt show up on the market tab. Also in "Portfolio" it is not showing up in the "transactions" or the "my markets" tab.

**Comment by elie222** [comment] 2018-07-11 11:37
I believe I have the same issue with my txs too:

https://etherscan.io/tx/0x6fe27d19565ff50da413f36b21adea016091e1d0cdf79126ceb0d9a3474ac37f

https://etherscan.io/tx/0xd180138cf7e03cd4e0fe47e82932aab939dd68b74441568365c1925cfac503fb

**Comment by Alorky** [comment] 2018-07-11 13:47
I had the same problem. Here is my transaction:

https://etherscan.io/tx/0xef4b3e3a7d38ad7c3a397a02585c3f32ab3a8ccab44e3a2f0806240b05f2601b

I looked into it a bit further and saw that the Augur smart contract was returning a random token named SHARE to people

https://etherscan.io/token/0x4a482975a31bb27b9f5cf84c07474b8446bb730c?a=0x39c230f89981274177e79708c921582bd4bd0303

here is the transaction of the contract returning these tokens to my wallet

https://etherscan.io/tx/0xfc9930b1c3322d2362f629aef45cdc4cc8141681b5b0e2e57110e77b0cf87c98

Any help explaining what is going on would be much appreciated!

**Comment by goyb** [comment] 2018-07-11 14:32
I solved it by deleting the augur-1.db file. On windows it is found at ~\Appdata\Roaming\Augur. Restarting and resyncing the app, it now shows the correct data.

I guess this is a duplicate:
Duplicate of #78

**Comment by Alorky** [comment] 2018-07-11 14:38
I think this problem differs from that described in #78. My issue is not in relation to making a new market but instead placing an order on an existing market

**Comment by goyb** [comment] 2018-07-11 16:07
@Alorky You are right. I created an order, which indeed did not show up. I removed the database and resynced to the network, but still it doesn't show up in the "transactions" or "positions" tab.

Transaction:
https://etherscan.io/tx/0xc1a3930efae6268e7250bef36d6be74ff54ce534043f4e5a2916f070ec390c7a

**Comment by zethraeus** [comment] 2018-07-11 17:43
Here are two more which are unaffected by resetting the database in 1.0.2
https://etherscan.io/tx/0x3949d032a5fbbd42dca6a1b242fe7e2fdae5e6aa0f07a6fea28388139d79e697
https://etherscan.io/tx/0x87d1484722734718dfd31696ef8d025f128bc77fffc5aeb714b444aec10a7d20

**Comment by nuevoalex** [comment] 2018-07-11 17:48
Right now to delete the DB you have to be connected to the Ethereum endpoints before pressing the button to Reset (This is being made more clear in the UI currently)

If you want to be absolutely sure you've deleted the DB you can still do so manually by deleting the .db files in you application data directory:

Mac OSX : ~/Library/Application\ Support/augur

Windows : %AppData%\augur

Linux : ~/.augur

**Comment by gabbello** [comment] 2018-07-11 18:37
An update to 1.0.2 and delete of the db/resynch made my order appear.

**Comment by justinbarry** [comment] 2018-07-11 23:03
This looks to be resolved with the remedial steps above. Closing.

**Comment by justinbarry** [comment] 2018-07-11 23:03
Related to #78

**Closed by justinbarry** 2018-07-11 23:03 UTC
