### ISSUE TITLE
Augur App cannot read balance of metamask account that I have made multiple bets with

### ISSUE THREAD

**Issue by bamos01** [AugurProject/augur-app#373] opened 2018-09-19 02:52 UTC
OS: Mac OSx
Version 1.5 and 1.5.1
Browser: Chrome
Description:  After upgrade to version 1.5, augur app was unable to read ETH / REP balances of my main metamask account that I have been using with the app for several weeks.  I can still see markets /bets and some old notifications, but all balances are read as '0'.  When I switch to a new account within metamask, it reads the balances correctly- so the error is specific to this one account.  I tried resyncing database but it did not help.  Also, I can use the account normally within metamask itself. 
 Any ideas?  thanks

**Comment by veox** [comment] 2018-09-19 18:36
Sounds to me like there's something in that account's history that makes it impossible to load in its entirety.

Just to clarify: have you used the account with other wallets?

Are you using a local Ethereum node as the backend? Or the default one given by choosing "Mainnet"?

Are there any error messages in the browser console? (In Chromium: right-click anywhere in the page, select "Inspect Element", switch to "Console" tab at the top. Should be something similar in Chrome.)

Any error messages in the log file? ([README in log file locations](https://github.com/AugurProject/augur-app#logging).)

**Comment by veox** [comment] 2018-09-19 18:53
You could also try creating a fresh browser profile, and importing the account there.

If that works, perhaps a "cache clear" on the original profile could help "fix" that profile, too; however, I wouldn't rush to do it if that's the case - might be valuable to determine what actually went wrong.

**Comment by veox** [comment] 2018-09-19 20:31
In my case, I guess it was caused by "suppressing" a transaction (same-`nonce` higher-`gas_price` empty-`data` via MyCrypto desktop app) that was meant to cancel an open order.

The order remained in display with "cancellation pending", and the next time I restarted the app, this issue surfaced.

**Comment by adrake33** [comment] 2018-09-20 16:33
Adding this issue to our internal tracking system: https://app.clubhouse.io/augur/story/16674/github-augur-cannot-read-balance-of-metamask-account

**Comment by bamos01** [comment] 2018-09-20 16:36
Deleting the chrome cache fixed the problem.  You can close.

**Comment by larspensjo** [comment] 2018-09-21 12:02
@adrake33 I have the same problem, please re-open again. In my case, (version 1.5.1) worked until I did a re-issue of a Metamask transaction with a higher fee.

**Comment by bthaile** [comment] 2018-09-21 15:07
See if hard refreshing your web browser helps. That will force loading fresh.

**Comment by veox** [comment] 2018-09-22 12:44
Re-confirming the cause being manipulating the transaction queue on the account, such as increasing the gas price or suppressing the transaction.

A simple "hard refresh" is insufficient to work around this. Only clearing site data helps.

This is a regression from v1.4.0, where I used to do this routinely.

Please do reopen for visibility.

**Comment by adrake33** [comment] 2018-09-23 00:32
Reopening and will investigate more.

**Comment by bamos01** [comment] 2018-09-23 12:27
It’s always only the same one account affected and it is the one I have used the most on Augur

**Comment by bthaile** [comment] 2018-09-25 16:11
We have a fix for this issue, seems to be an error with pulling user data from localStorage, reason for clearing the cache works. We have a fix coming out in next release.

**Comment by veox** [comment] 2018-10-01 11:48
I've tried to reproduce this with v1.6.1, and was no longer able to.

Guess OK to close issue.

**Closed** 2018-10-01 16:04 UTC
