### ISSUE TITLE
Random crashes on Windows 

### ISSUE THREAD

**Issue by matteopey** [AugurProject/augur-app#83] opened 2018-07-10 15:53 UTC
OS: Windows 10
Local node: parity 1.11.5

The app crash randomly, both using the local node or connecting to mainnet with Infura.
This is the log from `%appdata%/augur` folder.

```
[2018-07-10 17:25:19.838] [error] Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-created.js:20:29)
    at tryCatcher (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 17:25:19.838] [error] Error: market and outcome not found
    at db.first.from.where.asCallback (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-created.js:20:29)
    at tryCatcher (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

```
[2018-07-10 17:35:36.617] [error] Fatal Error, shutting down servers Error: Could not find balance for token decrease (token: 0xd5524179cb7ae012f5b642c1d6d700bbaa76b96b, owner: 0x7d50694af38dcd879255eb5f4dce53e4939c73ac)
    at db.first.from.where.asCallback (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\token\decrease-token-balance.js:13:29)
    at tryCatcher (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 17:35:36.617] [error] Error: Could not find balance for token decrease (token: 0xd5524179cb7ae012f5b642c1d6d700bbaa76b96b, owner: 0x7d50694af38dcd879255eb5f4dce53e4939c73ac)
    at db.first.from.where.asCallback (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\token\decrease-token-balance.js:13:29)
    at tryCatcher (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\matte\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by tobutridaz** [comment] 2018-07-10 22:28
I also get random crashes. Most crashes happen when connecting to mainnet (local Parity) and being synced at 99%. 

`[2018-07-11 00:21:45.777] [error] Fatal Error, shutting down servers Error: Could not find balance for token decrease (token: 0x4a482975a31bb27b9f5cf84c07474b8446bb730c, owner: 0x5e2130c995d105510467c2610893ab8464d3448d)
    at db.first.from.where.asCallback (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\token\decrease-token-balance.js:13:29)
    at tryCatcher (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

or when simply clicking through the markets
`
[2018-07-11 00:08:10.694] [error] Fatal Error, shutting down servers Error: market and outcome not found
    at db.first.from.where.asCallback (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\augur-node\build\blockchain\log-processors\order-created.js:20:29)
    at tryCatcher (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\tobun\AppData\Local\Programs\augur\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
`

**Comment by petervecchiarelli** [comment] 2018-07-11 20:46
Duplicate of #78 please track progress there.

**Closed by petervecchiarelli** 2018-07-11 20:46 UTC
