### ISSUE TITLE
Fatal Error, shutting down servers Error: order not found

### ISSUE THREAD

**Issue by aakilfernandes** [AugurProject/augur-app#89] opened 2018-07-10 17:21 UTC
Mac OSX High Sierra 10.13

```
[2018-07-10 13:09:46.813] [info] {"id":268,"jsonrpc":"2.0","method":"getMarketPriceCandlesticks","params":{"marketId":"0xe2d10bc6f5804e681deb12fd5f087ed16aaa989b","period":3600,"start":1531155600,"end":1531242547,"outcome":"1"}}
[2018-07-10 13:09:52.611] [info] block removed: 5940039
[2018-07-10 13:09:52.612] [info] Processing 1 logs
[2018-07-10 13:09:52.615] [info] new block: 5940039 1531242377
[2018-07-10 13:09:52.622] [info] Processing 16 logs
[2018-07-10 13:09:52.648] [error] Fatal Error, shutting down servers Error: order not found
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-filled/index.js:36:37)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 13:09:52.649] [error] Error: order not found
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-filled/index.js:36:37)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-10 13:09:52.649] [info] Stopping Augur Node Server
[2018-07-10 13:09:52.649] [info] Stopping Augur Node Server
[2018-07-10 13:09:52.650] [info] Stopping Augur UI Server
[2018-07-10 13:09:52.652] [info] Failed to startup: order not found
```

**Comment by page1** [comment] 2018-07-10 18:38
Got something pretty similar in my log

**Comment by petervecchiarelli** [comment] 2018-07-11 20:47
Duplicate of #78  please track progress there.

**Closed** 2018-07-12 06:01 UTC
