### ISSUE TITLE
Order book with equal bid & ask price

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#167] opened 2018-07-14 05:35 UTC
I'm not sure how this can happen, I was under the assumption that if bid == ask price then orders should be filled.
<img width="532" alt="screen shot 2018-07-13 at 11 32 04 pm" src="https://user-images.githubusercontent.com/6609556/42721265-2510eaec-86f5-11e8-8fa6-2a1499810403.png">

https://localhost:8080/#/market?description=will_donald_trump_be_impeached_before_the_end_of_his_first_term&id=0x96b9a092fd1d19d5dff566c07020d6f59d1db79e

**Comment by nuevoalex** [comment] 2018-07-14 08:29
@page1 You are correct. Looking into what might be going on here

**Comment by page1** [comment] 2018-07-17 19:57
Found another one
<img width="1186" alt="screen shot 2018-07-17 at 1 57 07 pm" src="https://user-images.githubusercontent.com/6609556/42842067-5841b6fe-89c9-11e8-8c0f-42d88d93abcf.png">

**Comment by petervecchiarelli** [comment] 2018-07-18 16:32
https://app.clubhouse.io/augur/story/14196/github-order-book-with-equal-bid-ask-price

**Comment by page1** [comment] 2018-07-18 17:14
<img width="1194" alt="screen shot 2018-07-18 at 11 14 28 am" src="https://user-images.githubusercontent.com/6609556/42896976-c5edbbe6-8a7b-11e8-9907-473ef0396733.png">

**Comment by nuevoalex** [comment] 2018-07-19 04:01
@page1 A fix for this will be coming in an upcoming release

**Comment by sharkcrayon** [comment] 2018-07-27 11:56
@page1 This issue could have been caused by a number of things. Based on @nuevoalex's comments, it's likely due to the "orphaned orders" issue, where sometimes an order is placed that cannot be taken. The only solution is for the user that placed the order to cancel it. We now have notifications in place for this, so users will be alerted when an order that they've placed becomes orphaned and needs to be cancelled.

It's also possible to place orders via the API that do not trigger a fill (even if a fill is possible) which means a crossed order book may occur at times.

I'm going to close this on the assumption that this is either addressed or not actually a bug. Please let us know if you see it again.

**Closed by sharkcrayon** 2018-07-27 11:56 UTC
