### ISSUE TITLE
Fail to connect using ubuntu 14.04

### ISSUE THREAD

**Issue by mostar** [AugurProject/augur-app#190] opened 2018-07-18 11:50 UTC
Hi,

It fail after pressing "connect" using the default configuration.
Version 1.0.4. 

Error message:

[14:45:22.191] [info] network name Mainnet
[14:45:22.284] [info] Starting Augur UI Server
[14:45:22.285] [info] Looking for certificate files in /home/username/.augur
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/augur","ws":"wss://mainnet.infura.io/ws"}
websocket wss://mainnet.infura.io/ws opened
connected to ethereum
[14:45:54.951] [info] /home/ramia/.augur/augur-1-syncing-2.db
/opt/augur/augur: relocation error: /tmp/.org.chromium.Chromium.ExGh5D: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

Thank you

**Comment by petervecchiarelli** [comment] 2018-07-18 16:51
https://app.clubhouse.io/augur/story/14206/github-fail-to-connect-using-ubuntu-14-04

**Comment by petervecchiarelli** [comment] 2018-07-20 07:23
Duplicate of #204  Please follow progress there.

**Comment by mostar** [comment] 2018-07-20 09:17
Are you sure its Duplicate to  #204. Not the same errors.

**Comment by bthaile** [comment] 2018-07-24 02:54
Do you have a snippet of the log where is failing with gethstar endpoint?

Also here are some other endpoints to try. You can also try just http(s) endpoint. You dont have to have both. 

https://predictions.global/augur-public-ethereum-nodes

**Comment by sharkcrayon** [comment] 2018-07-27 11:44
@mostar Any feedback on @bthaile's questions?

**Comment by mostar** [comment] 2018-07-27 12:23
gethstar.com


[15:21:44.042] [info] Starting Augur UI Server
[15:21:44.042] [info] Looking for certificate files in /home/myuser/.augur
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://gethstar.com/ethereum-http","ws":"ws://gethstar.com/ethereum-ws"}
websocket ws://gethstar.com/ethereum-ws opened
connected to ethereum
[15:21:47.080] [info] /home/myuser/.augur/augur-1-syncing-2.db
/opt/Augur/augur: relocation error: /tmp/.org.chromium.Chromium.srKF8e: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference




mainnet.infura.io


[15:19:41.059] [info] Starting Augur UI Server
[15:19:41.059] [info] Looking for certificate files in /home/myuser/.augur
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/augur","ws":"wss://mainnet.infura.io/ws"}
websocket wss://mainnet.infura.io/ws opened
connected to ethereum
[15:19:44.458] [info] /home/myuser/.augur/augur-1-syncing-2.db
/opt/Augur/augur: relocation error: /tmp/.org.chromium.Chromium.rojygX: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference


kovan.augur.net


[15:20:20.516] [info] network name Kovan
[15:20:24.754] [info] Starting Augur UI Server
[15:20:24.754] [info] Looking for certificate files in /home/myuser/.augur
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://kovan.augur.net/ethereum-http","ws":"wss://kovan.augur.net/ethereum-ws"}
websocket wss://kovan.augur.net/ethereum-ws opened
connected to ethereum
[15:20:27.915] [info] /home/myuser/.augur/augur-42-syncing-2.db
/opt/Augur/augur: relocation error: /tmp/.org.chromium.Chromium.xUC13e: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by justinbarry** [comment] 2018-07-31 02:18
@mostar Are you using the binary from the release page or building it?

**Comment by mostar** [comment] 2018-07-31 05:13
From release page.

**Comment by petong** [comment] 2018-07-31 16:43
This appears to be a mismatch in glibc versions. I will test on Ubuntu 14.04 shortly to verify.

**Comment by petong** [comment] 2018-07-31 20:30
glibc on 14.04 is quite old, 2.19. I don't think we plan on supporting 14.04 since the release date was July 24, 2014 and End Of Life was April 2019.

**Closed** 2018-08-01 08:42 UTC
Labels: bug, wontfix
