### ISSUE TITLE
Service exited with abnormal code: 1

### ISSUE THREAD

**Issue by TacoByte** [AugurProject/augur-app#77] opened 2018-07-10 10:36 UTC
High Sierra

The desktop app has crashed and exited on me twice with the following:
`com.apple.xpc.launchd[1] (com.electron.augur.7984[757]): Service exited with abnormal code: 1`

augur helper also spits this out once in a while, though it might not be related
`LSExceptions shared instance invalidated for timeout.`

**Comment by TacoByte** [comment] 2018-07-10 10:59
The crash happens when a new market is mined while the app is running! I have verified this comparing the crash timestamps to tx being confirmed on https://etherscan.io/address/0xe991247b78f937d7b69cfc00f1a487a293557677 (crash happens within 1-2 secs after block is mined)

**Comment by TacoByte** [comment] 2018-07-10 11:17
Note: this does not happen with all new markets

**Comment by TacoByte** [comment] 2018-07-10 11:52
Now, app seems to have crashed on its own, though maybe this is related to another state change (maybe somebody just placed a bet on a market?). or maybe it's something else. can't verify for sure right now

**Comment by TacoByte** [comment] 2018-07-11 04:36
[2018-07-11 01:31:18.694] [info] 
[2018-07-11 01:31:58.856] [info] new block: 5941588 1531265409
[2018-07-11 01:31:58.874] [info] new block: 5941589 1531265441
[2018-07-11 01:31:58.898] [info] Processing 2 logs
[2018-07-11 01:31:58.909] [error] Fatal Error, shutting down servers Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[2018-07-11 01:31:58.910] [error] Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[2018-07-11 01:31:58.953] [info] Stopping Augur Node Server
[2018-07-11 01:31:58.953] [info] Stopping Augur Node Server
[2018-07-11 01:31:58.954] [info] Stopping Augur UI Server
[2018-07-11 01:31:59.036] [info] Failed to startup: update `balances` set `balance` = '-15000000000000' where `token` = '0xbc940a98916afdaa955a1959cbe00c2d0efb01e5' and `owner` = '0x4a18c9f1e93e600b9bfabe914503819c0f93c0a1' - SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

**Comment by TacoByte** [comment] 2018-07-11 04:47
Crash happened in relation to an address holding REP and a different token (SHARE?)

https://etherscan.io/address/0xbc940a98916afdaa955a1959cbe00c2d0efb01e5
https://etherscan.io/address/0x4a18c9f1e93e600b9bfabe914503819c0f93c0a1

**Comment by justinbarry** [comment] 2018-07-11 20:42
Duplicate of #78. Please track progress there.

**Closed by justinbarry** 2018-07-11 20:42 UTC
