### ISSUE TITLE
augur app stuck on 70.58% sync

### ISSUE THREAD

**Issue by d1gitalflow** [AugurProject/augur-app#194] opened 2018-07-18 17:58 UTC
Infura seems to have troubles to seed augur?

![augur1](https://user-images.githubusercontent.com/26913156/42898932-7baa378a-8abc-11e8-921f-ed417cec642c.JPG)

**Comment by Anastik** [comment] 2018-07-19 18:38
Your best bet is to use augur.casino if you want to interact with the Augur App. I've had similar issues, too. The way I've found to fix it is simply reopening the app. Maybe even do a complete reinstall of v 1.0.4.

**Comment by petervecchiarelli** [comment] 2018-07-20 07:22
Duplicate of #204  Please follow progress there.

**Closed by petervecchiarelli** 2018-07-20 07:22 UTC
