### ISSUE TITLE
Disconnects when clicking submit when Purchasing " Participation Tokens " 

### ISSUE THREAD

**Issue by fadisaaida** [AugurProject/augur-app#113] opened 2018-07-11 03:04 UTC
[log.txt](https://github.com/AugurProject/augur-app/files/2182791/log.txt)
i use windows 10 64bit, chrome latest version, all my other ethereum nodes ( parity,geth ) closed, using the augur app with infura mainnet. 

once i open the app and connect to my ledger, i go to dispute tab and try to purchase some tokens, after the review page i click submit and then app disconnect from the ethereum node, the app itself
 does not crash.

**Comment by petervecchiarelli** [comment] 2018-07-12 17:46
https://app.clubhouse.io/augur/story/13773/github-disconnects-when-clicking-submit-when-purchasing-participation-tokens

**Comment by Metang386** [comment] 2018-07-13 15:12
same issue using infura.

**Comment by joeykrug** [comment] 2018-07-13 21:16
This seems to be an issue a lot of people are having

**Comment by fafrd** [comment] 2018-07-16 03:01
I have a similar (but not quite same) problem. Mine seems to stay connected to the eth node, but just spits "Error: unknown account" to the console: 
![image](https://user-images.githubusercontent.com/5905628/42741738-e1eeb48a-8882-11e8-9547-819194ec5a1e.png)

hoping this gets fixed before the window closes in 2 days 😬😬😬

**Comment by fafrd** [comment] 2018-07-17 01:18
still having this problem in 1.0.4

**Comment by nuevoalex** [comment] 2018-07-17 06:02
Discovered the cause of the problem. Should be fixed in an upcoming release when this gets merged and released: https://github.com/AugurProject/augur-ui/pull/2020

**Comment by sharkcrayon** [comment] 2018-08-01 12:36
This should be fixed now. Closing.

**Closed by sharkcrayon** 2018-08-01 12:36 UTC
