### ISSUE TITLE
add file containing build hashes to future releases

### ISSUE THREAD

**Issue by whereyouatwimm** [AugurProject/augur-app#173] opened 2018-07-16 06:59 UTC
hello

Just wanted to start a conversation around adding a file containing hashes for each executable produced during a designated release, preferably signed by a public pgp key for the project, to future releases. Currently, there is no secure manual verification.

wimm

**Comment by petong** [comment] 2018-07-17 00:15
dupe of issue #132

**Closed by petong** 2018-07-17 00:15 UTC
